 on:
   push:
     branches:
       - master

jobs:
  run_test:
    uses: MicroFocus/lrc-gh-action@v1.0.11
    with:
      lrc_server: 'https://loadrunner-cloud.saas.microfocus.com'
      lrc_tenant: '826316214'
      lrc_project: '5'
      lrc_test_id: '163'
      lrc_output_dir: './perf'
    secrets:
      LRC_CLIENT_ID: ${{ secrets.LRC_CLIENT_ID }}
      LRC_CLIENT_SECRET: ${{ secrets.LRC_CLIENT_SECRET }}
  print_run_id:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: run_test
    steps:
      - run: echo "LRC Run ID is ${{ needs.run_test.outputs.lrc_run_id }}"